/*jslint node: true, strict:implied, esversion: 6 */

var path = require('path'),
    env = process.env.NODE_ENV || 'development',
    webpackDigest = null;

/**
 * generating the file path based on map in webpack-assets.json, which is
 * being generated by [forgot the name of the package]
 * webpack-assets.json must be written to folder public/build
 * relative to the app root.
 * it creates an unhashed file path in development node and a hashed file path
 * in production mode.
 * @param {string} assetName the file name
 * @param {string} assetType the file extension without dot
 * @return {string} the file path
 */
function assetPath(assetName, assetType) {

    if (env === 'production') {

        try {
            webpackDigest =
                webpackDigest || require(path.resolve('public/build/webpack-assets.json'));
            let prodAssetPath = webpackDigest[assetName][assetType];

            return prodAssetPath;

        } catch (err) {
            console.error(err);
            console.error(err.stack);
        }
    }

    return '/build/' + assetName + '.' + assetType;

}

module.exports = assetPath;
