const
  path = require('path'),
  env = process.env.NODE_ENV || 'development',
  defaultDigestPath = 'public/build/webpack-assets.json';

/**
 * generating the file path based on map in webpack-assets.json, which is
 * being generated by [forgot the name of the package]
 * webpack-assets.json must be written to folder public/build
 * relative to the app root.
 * it creates an unhashed file path in development node and a hashed file path
 * in production mode.
 * @param {string} assetName the file name
 * @param {string} assetType the file extension without dot
 * @param {string} customDigestPath if path is not defaultDigestPath
 * @return {string} the file path
 */
function assetPath(assetName, assetType, customDigestPath) {

  let
    digestPath = customDigestPath || defaultDigestPath,
    prodAssetPath = '',
    webpackDigest;

  if (env === 'production') {

    try {
      webpackDigest =
        webpackDigest || require(path.resolve(digestPath));

      if (!webpackDigest) {
        throw new Error(`webpackDigest not found with path "${digestPath}"`);
      }

      if (!webpackDigest[assetName]) {
        throw new Error(`webpackDigest asset not found with assetName "${assetName}"`);
      }

      if (!webpackDigest[assetName][assetType]) {
        throw new Error(`webpackDigest assetName "${assetName}" not found with assetType "${assetType}"`);
      }

      prodAssetPath = webpackDigest[assetName][assetType];

    } catch (err) {
      console.error(err);
      console.error(err.stack);

      prodAssetPath = "assetPath error could not find asset path";

    } finally {
      return prodAssetPath;
    }
  }

  return '/build/' + assetName + '.' + assetType;

}

module.exports = assetPath;
